version: "3"
services:
  api:
    build: .
    ports:
      # - <port on localhost>:<port on container>
      - 12345:12345
    env_file:
      - ./.env
    environment: 
      # - NOME_VARIABLIE=VALORE

  postgres:
    image: